### ISSUE TITLE
Prevent usage as a webpack loader

### ISSUE THREAD

**Issue by jedmao** [cssnext/postcss-cssnext#1]
See https://github.com/cssnext/cssnext/issues/61

@MoOx is this something we need for the plugin as well?

**Comment by MoOx** [comment]
I think nobody will try to do use postcss-cssnext as a loader.
Webpack try {name}-loader by default, so if you have cssnext-loader, using "cssnext" will call cssnext-loader. But if you just have cssnext, it will use cssnext.
We don't need to handle this issue imo.
