### ISSUE TITLE
Publish npm package

### ISSUE THREAD

**Issue by jedmao** [cssnext/postcss-cssnext#10]
@MoOx the pleeease-filters plugin was [bumped to v2.0.0](https://github.com/cssnext/postcss-cssnext/commit/4d8eada1d2b968beadd3fca5c34c2fa12f10b4d1) and the deprecation warnings are [no longer showing](https://travis-ci.org/cssnext/postcss-cssnext/jobs/80201063#L314-L385). Is there anything else that needs to be done before we publish this plugin?

**Comment by MoOx** [comment]
2.0 is out :)
