### ISSUE TITLE
Error: require(...) is not a function

### ISSUE THREAD

**Issue by jedmao** [cssnext/postcss-cssnext#11]
I'm getting an error when requiring this plugin:

```
$ gulp styles
Requiring external module babel-core/register
z:\project\gulpfile.babel.js:78
    require('postcss-cssnext')({

                              ^

TypeError: require(...) is not a function
```

If I dig into the babel-generated code and replace `exports["default"] =` with `module.exports =` then everything works fine. The generated code doesn't look really any different than other plugins I've authored, however, which leaves me lost as to how this error is happening.

@MoOx, any ideas?

**Comment by jedmao** [comment]
Compare the non-working https://github.com/cssnext/postcss-cssnext/blob/master/src/index.js#L9 with the working https://github.com/jedmao/postcss-triangle/blob/master/lib/plugin.ts#L7

**Comment by MoOx** [comment]
It's because of babel way to handle es6 exports: if there is one thing only, it create the following code:

```js
exports["default"] = /* your default export */;
module.exports = exports["default"];
```

That said, postcss-cssnext also expose `features`. I move those as a property of the plugin.

**Comment by jedmao** [comment]
Thanks @MoOx for the fix in https://github.com/cssnext/postcss-cssnext/commit/432e2f50a52889a228a1c2d691080d556824adc4!
