### ISSUE TITLE
Plugin list

### ISSUE THREAD

**Issue by jedmao** [cssnext/postcss-cssnext#2]
Support the following [cssnext features](http://cssnext.io/features/) / plugins in the following order:
- [ ] [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties)
- [ ] [postcss-calc](https://github.com/postcss/postcss-calc)
- [ ] [postcss-custom-media](https://github.com/postcss/postcss-custom-media)
- [ ] [postcss-media-minmax](https://github.com/postcss/postcss-media-minmax)
- [ ] [postcss-custom-selectors](https://github.com/postcss/postcss-custom-selector)
- [ ] [postcss-color-rebeccapurple](https://github.com/postcss/postcss-color-rebeccapurple)
- [ ] [postcss-color-hwb](https://github.com/postcss/postcss-color-hwb)
- [ ] [postcss-color-gray](https://github.com/postcss/postcss-color-gray)
- [ ] [postcss-color-hex-alpha](https://github.com/postcss/postcss-color-hex-alpha)
- [ ] [postcss-color-function](https://github.com/postcss/postcss-color-function)
- [ ] [postcss-font-variant](https://github.com/postcss/postcss-font-variant)
- [ ] [pleeease-filters](https://github.com/iamvdo/pleeease-filters)
- [ ] [pixrem](https://github.com/robwierzbowski/node-pixrem)
- [ ] [postcss-pseudoelements](https://github.com/axa-ch/postcss-pseudoelements)
- [ ] [postcss-selector-matches](https://github.com/postcss/postcss-selector-matches)
- [ ] [postcss-selector-not](https://github.com/postcss/postcss-selector-not)
- [ ] [postcss-pseudo-class-any-link](https://github.com/jonathantneal/postcss-pseudo-class-any-link)
- [ ] [postcss-color-rgba-fallback](https://github.com/postcss/postcss-color-rgba-fallback)
- [ ] [autoprefixer](https://github.com/postcss/autoprefixer)

**Comment by MoOx** [comment]
You probably don't need an issue for all plugins cssnext currently have. Maybe one is enough ?

**Comment by jedmao** [comment]
@MoOx the issue comment has been updated to reflect all feature plugins in the appropriate order.

**Comment by jedmao** [comment]
Do we know of any plugins listed above as being async? Or can we keep this plugin sync?

**Comment by MoOx** [comment]
I don't think any is being async. Only postcss-import was but since we won't use it here...

**Comment by MoOx** [comment]
Closed by 467156c00fe0558abdf788b6a01ba01cb7cfa87d
