### ISSUE TITLE
Any value in supporting a plugins option?

### ISSUE THREAD

**Issue by jedmao** [cssnext/postcss-cssnext#5]
Refer to https://github.com/cssnext/cssnext/issues/118

I personally don't think there's any value of implementing this option in this plugin, because they can just:

```js
postcss(
  require('postcss-cssnext')(/* options */),
  // more plugins...
)
```

**Comment by MoOx** [comment]
just to pass options to the plugins that cssnext add ? like custom-properties variables defined via js...

**Comment by MoOx** [comment]
what about the browser option to enable/disable automatically ?

**Comment by jedmao** [comment]
No no. I mean the "plugins" option, like:

```js
{
  plugins: [
    require("postcss-stuff"),
    require("postcss-more-stuff"),
    // custom transformation code
    function(cssAst, result) {
      // see https://github.com/postcss/postcss
    },
  ],
}
```

**Comment by MoOx** [comment]
Oh sure, doesn't make sense at all here
