### ISSUE TITLE
Any reason to add the postcss-browser-reporter to this plugin?

### ISSUE THREAD

**Issue by jedmao** [cssnext/postcss-cssnext#6]
See https://github.com/cssnext/cssnext/issues/88

I'm thinking this also has no place in this plugin, because the user can implement the [postcss-browser-reporter](https://github.com/postcss/postcss-browser-reporter) plugin themselves, not just for cssnext, but any other plugins they are using.

Unless there's something particularly special about the cssnext use case here and we want to keep the styling introduced in https://github.com/cssnext/cssnext/issues/88. Or at least have the option?

What do you think?

**Comment by MoOx** [comment]
Maybe you can drop it here. I will keep it in the cssnext project.
